version: '3.7'
services: 
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports: 
            - 8090:80
        environment: 
            PMA_ARBITRARY: 1
        networks: 
            - local_lempp
        restart: always
    mariadb:
        image: yukitoki/mariadb:10.4
        container_name: mariadb
        volumes: 
            - local_mariadb:/var/lib/mysql
        environment: 
            MYSQL_ROOT_PASSWORD: HatsuneMiku01
        restart: always
        networks: 
            - local_lempp
    nginx:
        image: yukitoki/nginx-alpine-ssl
        container_name: nginx
        ports: 
            - 80:80
            - 443:443
        volumes: 
            - $PWD/nginx/conf.d:/etc/nginx/conf.d
            - $PWD/nginx/app:/var/www/html
            - $PWD/nginx/ssl:/etc/ssl/private
            - $PWD/nginx/ssl:/etc/ssl/certs
        environment: 
            CRT: nginx.crt
            KEY: nginx.key
        networks: 
            - local_lempp
        links: 
            - php7.2-fpm
        restart: always
    php7.2-fpm:
        image: yukitoki/php:7.2-fpm
        container_name: php7.2-fpm
        ports: 
            - 9072:9000
        volumes: 
            - ./nginx/app:/var/www/html
        links: 
            - mariadb
        restart: always
        networks: 
            - local_lempp
networks: 
    local_lempp:
        name: local_lempp
volumes: 
    local_mariadb:
        external: true